### PR TITLE
gug changes🔥🔥🔥

### PR DESCRIPTION
**Pull request by KobeniSilly**
Changes:
  - Renamed workflow to Build SkyblockFeatures
  - Changed Java distribution to Zulu
  - Bump Gradle from v8.3 to v8.5
  - Renamed uploaded artifact to SkyblockFeatures-Nightly

### CODE REVIEW

**Comment by MrFast-js** [comment]
What is the benefit of newer gradle, and swapping to Zulu, and I'm stupid what is nightly 💀

Also what's your discord so I can add u as contributor in the discord

**Comment by KobeniSilly** [comment]
updating gradle because faster build time
not sure why i switched to Zulu but its good :D
nightly refers to a build or release that is generated automatically on a daily basis :D

**Comment by MrFast-js** [comment]
Ah that makes sense now, 2 more things what's your discord and what in the world is "gug" inside of gug changes 🔥🔥🔥

**Comment by KobeniSilly** [comment]
discord `kobenisilly`

gug means good :3

**Pull request merged**
